name: ci-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Prepare docker variables
      id: vars
      run: |
        set -x
        echo "##[set-output name=sha]$GITHUB_SHA"
        echo "##[set-output name=timestamp]$(date +%s)"
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.3.0
      with:
        tags: |
          ghcr.io/beryju/imagik:latest
          ghcr.io/beryju/imagik:latest-${{ steps.vars.outputs.timestamp }}-${{ steps.vars.outputs.sha }}
        push: ${{ github.ref == 'refs/heads/master' }}
        platforms: linux/amd64,linux/arm64
        build-args: |
          GIT_BUILD_HASH=${{ steps.vars.outputs.sha }}
